Add controllers
Vexvl/java-shareit pull request #1
Opened 2023-07-01 02:15 UTC by Vexvl

2023-07-02 19:08 UTC, sergeymamonov requested changes
Рекомендую давать более емкие названия коммитам и пулл реквестам.

2023-07-02 19:08 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/exception/ExceptionsHandler.java
> +    }
Лучше еще добавить обработку рантайм ошибок и ошибок валидации входных данных (500 и 400 статус коды).

2023-07-02 19:08 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/exception/ExistingException.java
> +public class ExistingException extends RuntimeException {
Из названия непонятно, то ли ошибка потому что уже что-то существует, то ли наоборот, чего-то не существует.

2023-07-02 19:08 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/exception/EmailExistence.java
> +public class EmailExistence extends RuntimeException {
Обычно все классы ошибок завершаются на ...Exception. И опять сделать более конкретное название класса ошибки.

2023-07-02 19:08 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/exception/InvalidRequestException.java
> +public class InvalidRequestException extends RuntimeException {
Этот класс где-то используется?

2023-07-02 19:08 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/repository/impl/UserRepositoryImpl.java
> +        if (user != null) {
При таком расположении проверок весь основной код метода сдвинут вправо. Можно проще и красивее.

if (user == null) {
    throw new IllegalArgumentException("User null");
}
и так далее другие проверки.
И уже код не нужно будет сдвигать вправо.

2023-07-02 19:08 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/repository/impl/UserRepositoryImpl.java
> +        if (usersMap.containsKey(ownerId)) {
if (!usersMap.containsKey(ownerId)) {
   throw new ExistingException("Такого user нет");
}
код метода.

2023-07-03 02:41 UTC, Vexvl commented on src/main/java/ru/practicum/shareit/user/repository/impl/UserRepositoryImpl.java
> +        if (usersMap.containsKey(ownerId)) {
Cпасибо за замечания, всё исправил

2023-07-03 21:28 UTC, sergeymamonov approved these changes

2023-07-03 21:28 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/exception/ExceptionsHandler.java
> +    @ExceptionHandler(EmailDuplicateException.class)
Нет, речь идет о RuntimeException. При возникновении такого исключения нужно возвращать HttpStatus.INTERNAL_SERVER_ERROR

2023-07-03 21:28 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/exception/AbsenceException.java
> +public class AbsenceException extends RuntimeException {
EntityNotFoundException обычно такую ошибку называют, то есть здесь есть существительное и понятно, почему возникает такая ошибка.

2023-07-03 21:28 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/exception/ExceptionsHandler.java
> +    @ExceptionHandler(InvalidRequestException.class)
Это исключение где-то в коде кидается?

2023-07-03 21:28 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/repository/impl/UserRepositoryImpl.java
> +        if (user.getName() != null) {
На 41 строке уже есть такая проверка.

2023-07-12 23:29 UTC, merged