Add bookings
Vexvl/java-shareit pull request #2
Opened 2023-07-16 19:02 UTC by Vexvl

2023-07-17 20:21 UTC, sergeymamonov requested changes

2023-07-17 20:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingDto changeBookingStatus(@RequestHeader("X-Sharer-User-Id") Long ownerId, @PathVariable Long bookingId, @RequestParam String approved) {
Старайтесь не выходить на длину строки в 120 символов.

2023-07-17 20:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        }
Лучше всегда делать ветку default на случай, если мы получим статус, который нам неизвестен, чтобы можно было кинуть ошибку или что-то еще сделать в такой ситуации. Проверьте везде, где используете switch.

2023-07-17 20:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        }
А еще лучше сделать approved логическим типом данных.

2023-07-17 20:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/handler/ExceptionsHandler.java
> +        return Map.of("error", "Такого элемента нет", "errorMessage", "Ошибка на сервере");
Ошибка на сервере везде выглядит немного странно. Тем более, что при получении невалидных данных никакой ошибки на сервере, в том понимании, что произошла какая-то непредвиденная ошибка, нет.

2023-07-17 20:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/handler/ExceptionsHandler.java
> +    public Map<String, String> handleEmailDuplicateException(EmailDuplicateException e) {
По названию ошибки это скорее 409 статус.

2023-07-17 20:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/handler/ExceptionsHandler.java
> +    public Map<String, String> handleUnknownStatusException(UnknownStatusException e) {
Скорее 400 статус.

2023-07-17 20:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +            List<Booking> nextBookingsList = bookingRepository.findNextOrderedBookingsByItemId(itemDto.getId());
Не очень хорошо делать запросы к БД в цикле. Это большая нагрузка на БД.

2023-07-17 20:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        ;
Лишняя точка с запятой.

2023-07-17 20:21 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +    status     VARCHAR                                 NOT NULL,
Размер varchar должен быть ограничен.

2023-07-18 03:16 UTC, Vexvl commented on src/main/resources/schema.sql
> +    status     VARCHAR                                 NOT NULL,
Спасибо за замечания, всё исправил

2023-07-18 05:06 UTC, sergeymamonov approved these changes
Устранить оставшиеся замечания.

2023-07-18 05:06 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/handler/ExceptionsHandler.java
> +    public Map<String, String> handleUnknownStatusException(UnknownStatusException e) {
Тут либо статус изменить, либо название ошибки, потому что неизвестный статус не должен вызывать 500 ответ. 500 ответ - это ошибка в коде.

2023-07-18 05:06 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +                    commentRepository.findAllByItem(item));
Запрос к БД в цикле.

2023-07-19 21:37 UTC, merged