Add-docker
Vexvl/java-shareit pull request #5
Opened 2023-07-31 21:03 UTC by Vexvl

BookingClient.java
       BookingController.java
       BookingState.java
       BookItemRequestDto.java
       CommentClient.java
       CommentController.java
       CommentDto.java
       docker-compose.yml
       Dockerfile
       Dockerfile
       EmailDuplicateException.java
       ExceptionsHandler.java
       ItemClient.java
       ItemController.java
       ItemDto.java
       ItemRequestClient.java
       ItemRequestController.java
       ItemRequestDto.java
       ItemUnavailableException.java
       NoBookingException.java
       OwnerBookingException.java
       pom.xml
       pom.xml
       ShareItGateway.java
       UserClient.java
       UserController.java
       UserDto.java
       WrongDateBookingException.java

2023-08-01 14:52 UTC, sergeymamonov requested changes
BookingServiceImpl строка 49 эту проверку можно сделать в gateway?

Где используются исключения из пакета gateway/src/main/java/ru/practicum/shareit/item/exception

2023-08-01 14:52 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/handler/ExceptionsHandler.java
> +    public Map<String, String> handleEmailDuplicateException(EmailDuplicateException e) {
А как вы проверяете, что уже используется этот email, без запроса к БД? И остальные исключения, которые здесь обрабатываются тоже проверьте, могу ли они возникнуть в сервисе gateway.

2023-08-01 14:52 UTC, sergeymamonov commented on gateway/.gitignore
> +target/
Файл гитигнор должен быть только один и лежать он должен в корне проекта. Один репозиторий, один файл гитигнор.

2023-08-01 14:52 UTC, sergeymamonov commented on pom.xml
> +    <packaging>pom</packaging>
Указывать зависимости в родительском помнике не очень хорошая практика. Лучше указывать все зависимости в дочерних помниках. Пример, нужна зависимость для каждого из подмодулей, но в одном нужна версия 1, а во втором версия 2. Если указывать зависимость в дочерних помниках, то легко указать в одном одну версию, а во втором другую версию.

2023-08-01 14:52 UTC, sergeymamonov commented on server/.gitignore
> +target/
Лишний файл.

2023-08-01 19:43 UTC, Vexvl commented on server/.gitignore
> +target/
Спасибо за замечания, всё исправил

2023-08-02 06:38 UTC, Vexvl commented
Извините, не до конца исправил все тесты на гитхабе

2023-08-02 21:59 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/handler/ExceptionsHandler.java
> +        return new ResponseEntity<>("An unexpected error occurred", HttpStatus.BAD_REQUEST);
Может быть планировалось INTERNAL_SERVER_ERROR возвращать?

2023-08-02 21:59 UTC, sergeymamonov commented on server/.gitignore
> +target/
Не увидел изменений в BookingServiceImpl строка 49, проверка bookingDto.getStart().isBefore(bookingDto.getEnd() осталась.

2023-08-03 02:13 UTC, closed without merging